# Generated by Django 6.0.3 on 2026-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_episode_historicalepisode_notes_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalseason',
            name='is_ignored',
        ),
        migrations.RemoveField(
            model_name='season',
            name='is_ignored',
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicmedia',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalanime',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbasicmedia',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcomic',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmanga',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmovie',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalseason',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltv',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='Completed', max_length=20),
        ),
    ]
