# Generated by Django 5.2.9 on 2026-04-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_move_specials_override_to_item'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='episodewatch',
            new_name='app_episode_related_d86b00_idx',
            old_name='app_episode_related_521822_idx',
        ),
        migrations.RenameIndex(
            model_name='episodewatch',
            new_name='app_episode_related_61bcad_idx',
            old_name='app_episode_related_b6b5fd_idx',
        ),
        migrations.AlterField(
            model_name='episodewatch',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Origin of the watch event (manual, bulk, import, webhook).', max_length=30),
        ),
    ]
