version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-dev:
        patterns: ["*"]
        update-types: ["minor", "patch"]
        dependency-type: "development"
      python-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]
        dependency-type: "production"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-compose-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]
