# Generated by Django 5.1.5 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_alter_customlist_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customlist",
            name="import_source",
            field=models.CharField(
                blank=True,
                choices=[("trakt", "Trakt")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customlist",
            name="import_source_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="customlist",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("import_source", ""), ("import_source_id", ""))
                    | (
                        ~models.Q(("import_source", ""))
                        & ~models.Q(("import_source_id", ""))
                    )
                ),
                name="lists_customlist_import_source_fields_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="customlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("import_source__gt", ""),
                    ("import_source_id__gt", ""),
                ),
                fields=("owner", "import_source", "import_source_id"),
                name="lists_customlist_unique_import_source_per_owner",
            ),
        ),
    ]
