# Generated by Django 5.1.7 on 2025-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_add_quick_watch_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="list_detail_sort",
            field=models.CharField(
                choices=[
                    ("date_added", "Date Added"),
                    ("title", "Title"),
                    ("media_type", "Media Type"),
                    ("rating", "My Rating"),
                ],
                default="date_added",
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_sort_valid",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("list_detail_sort__in", ["date_added", "title", "media_type", "rating"]),
                ),
                name="list_detail_sort_valid",
            ),
        ),
    ]
