# Generated by Django 6.0.3 on 2026-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_add_not_interested_remove_is_ignored'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0042_update_list_detail_sort_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='tv_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='season_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='movie_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='anime_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='manga_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='game_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='book_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='list_detail_status_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='anime_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='comic_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Not Interested', 'Not Interested')], default='All', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='list_detail_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tv_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='tv_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('season_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='season_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('movie_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='movie_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('anime_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='anime_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('manga_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='manga_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='game_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('book_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='book_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('comic_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Not Interested'])), name='comic_status_valid'),
        ),
    ]
